# Generated by Django 5.2.3 on 2025-06-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publishedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
