# Generated by Django 5.2.3 on 2025-07-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
